baseURL = 'https://yellow.luna.ovh/'
defaultContentLanguage = 'en'
title = 'yellow'
theme = 'hugo-theme-console'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = 'about/'
  url = 'about/'

  [[params.navlinks]]
  name = 'posts/'
  url = 'posts/'
  
  [[params.navlinks]]
  name = 'images/'
  url = 'images/'